name: Update README on Folder Creation

on:
  # Trigger the workflow on any push events
  push:
    branches:
      - main  # Adjust this based on your default branch name

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Determine if directory structure changed
        id: directory-changed
        run: |
          # Check if any new directories match the specified pattern
          if [ "$(ls -d ASVS_*/* 2>/dev/null)" != "" ]; then
            echo "Directory structure has changed."
            echo "::set-output name=changed::true"
          else
            echo "No changes in directory structure."
            echo "::set-output name=changed::false"
          fi

      - name: Generate Table and Update README
        if: steps.directory-changed.outputs.changed == 'true'
        run: |
          # Generate the Markdown table for the new directories
          table=""
          for dir in ASVS_*/*; do
              if [ -d "$dir" ]; then
                  link=$(echo "$dir" | sed 's/\//%2F/g' | sed 's/ASVS_/https:\/\/snbig.github.io\/Vulnerable-Pages\/ASVS_/g')
                  table+="| $(basename "$dir") | [ASVS Requirement]( $link ) |\n"
              fi
          done
          echo "$table" > table.md

          # Append the generated table to the README.md file
          cat table.md >> README.md

      - name: Commit and push changes
        if: steps.directory-changed.outputs.changed == 'true'
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@users.noreply.github.com'
          git add README.md
          git commit -m "Auto-update README with new folder information"
          git push
