name: Update README with new ASVS Vulnerable Page

on:
  push:
    branches: [ main ]

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install jq -y

      - name: Get list of ASVS folders
        id: folders
        run: |
          find . -type d -name 'ASVS_[0-9][0-9][0-9]' | sort

      - name: Parse folder names and generate table content
        id: table_content
        run: |
          folders=$(echo ${{ steps.folders.outputs }})
          content=""
          for folder in $folders; do
            id=$(basename "$folder")
            link="https://snbig.github.io/Vulnerable-Pages/$id/"
            content="$content\n| $id | [$id]($link) |"
          done
          echo ::set-output name=content::"$content"

      - name: Update README with table
        uses: seborama/update-readme@v2
        with:
          path: README.md
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pattern: "!ASISVS_TABLE!"
          replacement: |-
            ## ASVS Requirements

            | ASVS Req. ID | Link |
            |---|---|
            ${{ steps.table_content.outputs.content }}
