name: Update README Table

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Read existing table (optional)
        run: |
          set +e
          existing_table=$(cat README.md | grep -E '^<h2>ASVS Pages|<table>|</table>$')
          if [[ ! -z "$existing_table" ]]; then
            echo "Existing table found. Updating..."
          else
            echo "No existing table found. Creating new table..."
          fi
          folders=$(find . -type d -regex ".*/ASVS_[0-9]+_[0-9]+_[0-9]+")
          echo $folders
          content=""
          for folder in $folders; do
            req_id=$(basename "$folder" | sed 's/ASVS_\([0-9]\+\).\([0-9]\+\).\([0-9]\+\)/ASVS \1.\2.\3/')
            link="https://snbig.github.io/Vulnerable-Pages/${folder/.\//}"
            content+="<tr><td>$req_id</td><td><a href=\"$link\">$link</a></td></tr>\n"
          done
          # Append table content if no existing table found, otherwise replace the existing table content
          if [[ -z "$existing_table" ]]; then
            echo "<h2>ASVS Pages</h2>" >> README.md
            echo "<table>" >> README.md
            echo "<tr><th>ASVS Req. ID</th><th>Link</th></tr>" >> README.md
            echo -e "$content" >> README.md
            echo "</table>" >> README.md
          else
            sed -i '/<h2>ASVS Pages/,/<\/table>/d' README.md
            echo "<h2>ASVS Pages</h2>" >> README.md
            echo "<table>" >> README.md
            echo "<tr><th>ASVS Req. ID</th><th>Link</th></tr>" >> README.md
            echo -e "$content" >> README.md
            echo "</table>" >> README.md
          fi

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update README table
          commit_user_name: GitHub Actions
          commit_user_email: github-actions[bot]@users.noreply.github.com
          branch: main  # Replace with your desired branch
          file_pattern: README.md
