name: Update README on Folder Creation

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List directory contents
        run: |
          ls -R
          ls -d ASVS_*/*
          echo "Current directory: $(pwd)"

      - name: Determine if directory structure changed
        id: directory-changed
        run: |
          if [ "$(ls -d ASVS_*/* 2>/dev/null)" != "" ]; then
            echo "Directory structure has changed."
            echo "::set-output name=changed::true"
          else
            echo "No changes in directory structure."
            echo "::set-output name=changed::false"
          fi

      - name: Generate Table and Update README
        if: steps.directory-changed.outputs.changed == 'true'
        run: |
          table=""
          for dir in ASVS_*/*; do
              if [ -d "$dir" ]; then
                  link=$(echo "$dir" | sed 's/\//%2F/g' | sed 's/ASVS_/https:\/\/snbig.github.io\/Vulnerable-Pages\/ASVS_/g')
                  table+="| $(basename "$dir") | [ASVS Requirement]( $link ) |\n"
              fi
          done
          echo "Generated table:"
          echo "$table"
          echo "$table" > table.md

          echo "Content of table.md:"
          cat table.md

          cat table.md >> README.md

      - name: Show updated README
        run: cat README.md

      - name: Commit and push changes
        if: steps.directory-changed.outputs.changed == 'true'
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@users.noreply.github.com'
          git add README.md
          git commit -m "Auto-update README with new folder information"
          git push
