name: Update README with new ASVS folder

on:
  push:
    branches: [ main ]

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get list of ASVS folders
        id: folders
        run: |
          find . -type d | grep -E 'ASVS_[0-9]+_[0-9]+_[0-9]+' | sort

      - name: Parse folder names and generate table content
        id: table_content
        run: |
          folders=$(echo ${{ steps.folders.outputs }})
          content=""
          for folder in $folders; do
            id=$(basename "$folder")
            link="https://snbig.github.io/Vulnerable-Pages/$id/"
            content="$content| $id | [$id]($link) |"  # Removed extra newlines
          done
          echo ::set-output name=content::"$content"

      - name: Update README with table
        run: |
          folders=$(echo ${{ steps.table_content.outputs.content }})
          pattern="!ASISVS_TABLE!"
          replacement="## ASVS Requirements\n\n| ASVS Req. ID | Link |\n|---|---|"
          for folder in $folders; do
            id=$(basename "$folder")
            link="https://snbig.github.io/Vulnerable-Pages/$id/"
            replacement="$replacement\n| $id | [$id]($link) |"
          done
          replacement="$replacement\n"
          sed -i "s/$pattern/$replacement/" README.md

